### ISSUE TITLE
EPIC: Aplicação da lógica de edição de produtos (ADMIN) 🥇🟡 

### ISSUE THREAD

**Issue by plfmoura** [Juanpi92/Vegetanizando#36]
- Aplicação nova lógica de edição de produtos. ✅ 
- Utilização dos novos componentes na zona administrativa. ✅ 
- Alinhamento para adição dos alertas personalizados. ✅

**Comment by plfmoura** [comment]
Fico no aguardo para fazermos o alinhamento para aplicar os alertas personalizados @Juanpi92.

**Comment by Juanpi92** [comment]
Componente de edição de produtos feito e funcional

**Comment by plfmoura** [comment]
Alinhamento feito, aguardando atualização em produção. 🟢
